custom_structured_configuration_router_bgp:
  neighbors:
  - ip_address: 172.16.0.1
    peer_group: EVPN-OVERLAY-CORE
    description: BB1_OVERLAY
  - ip_address: 172.16.0.2
    peer_group: EVPN-OVERLAY-CORE
    description: BB2_OVERLAY
  - ip_address: 172.16.2.1
    peer_group: IPv4-UNDERLAY-PEERS
    description: BB1_UNDERLAY
  - ip_address: 172.16.2.3
    peer_group: IPv4-UNDERLAY-PEERS
    description: BB2_UNDERLAY
  address_family_ipv4:
    peer_groups:
      - name: IPv4-UNDERLAY-PEERS
        activate: true
  address_family_evpn:
    peer_groups:
      - name: EVPN-OVERLAY-CORE
        activate: true  
