---

csc_prefix_lists:
  - name: PL-GATEWAY-LOOP
    sequence_numbers:
      - sequence: 10
        action: 'permit 1.1.2.7/32'
      - sequence: 20
        action: 'permit 1.1.2.8/32'
      - sequence: 30
        action: 'permit 2.2.2.7/32'
      - sequence: 40
        action: 'permit 2.2.2.8/32'

csc_router_bgp:
  bgp:
    bestpath:
      d_path: true
  peer_groups:
    - name: EVPN-OVERLAY-CORE
      local_as: 65000
      remove_private_as:
        replace_as: true
      remote_as: 65000
      route_reflector_client: true
      update_source: Loopback0
      bfd: true
      ebgp_multihop: 15
      send_community: all
  neighbors:
    - ip_address: 172.16.2.0
      peer_group: IPv4-REMOTE-UNDERLAY-PEERS
      description: BB1_UNDERLAY
    - ip_address: 172.16.2.4
      peer_group: IPv4-REMOTE-UNDERLAY-PEERS
      description: BB2_UNDERLAY
    - ip_address: 1.1.0.1
      peer_group:  EVPN-OVERLAY-CORE
      description: BB1_OVERLAY
    - ip_address: 1.1.0.2
      peer_group:  EVPN-OVERLAY-CORE
      description: BB2_OVERLAY
  address_family_evpn:
    peer_groups:
      - name: EVPN-OVERLAY-CORE
        activate: true
        domain_remote: true
        rcf_in: AS65000_IN_EVPN()
        rcf_out: AS65000_OUT_EVPN()
      - name: EVPN-OVERLAY-PEERS
        rcf_in: AS65200_IN_EVPN()
        rcf_out: AS65200_OUT_EVPN()
    neighbor_default:
      next_hop_self_received_evpn_routes:
        enable: true
        inter_domain: true
    domain_identifier: "2:2"
  address_family_ipv4:
    peer_groups:
      - name: IPv4-REMOTE-UNDERLAY-PEERS
        activate: true
        rcf_out: AS65000_OUT_IPV4()
      - name: EVPN-OVERLAY-CORE
        activate: false

csc_ethernet_interfaces:
  - name: Ethernet7
    mtu: 9214
  - name: Ethernet8
    mtu: 9214
