---

port_profiles:
  - profile: DEFAULT
    spanning_tree_portfast: edge
    mode: access

servers:
  - name: HostN
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF1, C-LEAF2 ]
        vlans: 10
        profile: DEFAULT
        port_channel:
          description: HostN
          mode: active

  - name: HostO
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF3 ]
        vlans: 20
        profile: DEFAULT
        description: HostO

  - name: HostP
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF3, C-LEAF4 ]
        vlans: 60
        profile: DEFAULT
        port_channel:
          description: HostP
          mode: active

  - name: HostQ
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF4 ]
        vlans: 50
        profile: DEFAULT
        description: HostQ

  - name: HostR
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 20
        profile: DEFAULT
        port_channel:
          description: HostR
          mode: active
  
  - name: HostS
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 60
        profile: DEFAULT
        port_channel:
          description: HostS
          mode: active
