---

port_profiles:
  - profile: DEFAULT
    spanning_tree_portfast: edge
    mode: access

servers:
  - name: A1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 10
        profile: DEFAULT
        port_channel:
          description: A1
          mode: active

  - name: A2
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 30
        profile: DEFAULT
        port_channel:
          description: A2
          mode: active

  - name: A3
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF3 ]
        vlans: 50
        profile: DEFAULT
        description: A3

  - name: A4
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF3, A-LEAF4 ]
        vlans: 10
        profile: DEFAULT
        port_channel:
          description: A4
          mode: active
        
  - name: A5
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF4 ]
        vlans: 30
        profile: DEFAULT
        description: A5

  - name: A6
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF5, A-LEAF6 ]
        vlans: 70
        profile: DEFAULT
        port_channel:
          description: A6
          mode: active
