---
type: backbone

custom_structured_configuration_router_bgp:
  listen_ranges:
    - prefix: 1.1.0.0/16
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65500

backbone:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 1.1.0.0/24
    bgp_as: 65500
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes: 
    - name: BB1
      id: 1 
      mgmt_ip: 192.168.0.9/24 
    - name: BB2
      id: 2
      mgmt_ip: 192.168.0.10/24
