---

dc_name: backbone
pod_name: pod-bb

type: backbone

backbone:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 1.1.0.0/24
    bgp_as: 65500
    
  nodes: 
    - name: BB1
      id: 1 
      mgmt_ip: 192.168.0.9/24 
    - name: BB2
      id: 2
      mgmt_ip: 192.168.0.10/24
