---
site_name: Arista Community Labs
site_url: https://aclabs.arista.com
repo_name: Arista Community Labs
repo_url: https://github.com/aristanetworks/aclabs

# extra_css:
#   - assets/stylesheets/extra.css

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # enabling prune for testing only, to check if it's stable
    #   it's not making any difference with current site setup
    - navigation.prune
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/gears

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # allows list ident with 2 spaces
  - mdx_truly_sane_lists

copyright: >
  &nbsp;&#x1F36A;&nbsp;<a href="#__consent">Change cookie settings</a>

plugins:
  - privacy
  - search

nav:
  - Home:
    - Home: index.md
