---
# ACT Server Topology Variable

non_fabric_nodes:
  - HostA1:
      ip_addr: 192.168.0.221
      node_type: veos
  - HostA2:
      ip_addr: 192.168.0.222
      node_type: veos
  - HostA3:
      ip_addr: 192.168.0.223
      node_type: veos
  - HostA4:
      ip_addr: 192.168.0.224
      node_type: veos
  - HostA5:
      ip_addr: 192.168.0.225
      node_type: veos
  - HostA6:
      ip_addr: 192.168.0.226
      node_type: veos
