---
servers:
  - name: HostA
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostA
          mode: active

  - name: HostB
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostB
          mode: active

  - name: HostC
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF3 ]
        vlans: 50
        mode: access
        spanning_tree_portfast: edge
        description: HostC

  - name: HostD
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF3, A-LEAF4 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostD
          mode: active
        
  - name: HostE
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF4 ]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        description: HostE

  - name: HostF
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF5, A-LEAF6 ]
        vlans: 70
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostF
          mode: active
