---
fabric_name: FABRIC 

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

underlay_multicast: true
evpn_multicast: true

fabric_ip_addressing:
  mlag:
    algorithm: same_subnet

bgp_peer_groups:
  evpn_overlay_core:
    structured_config:
      local_as: 65000
      remove_private_as:
        replace_as: true
      bfd: false

l3_edge:
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    DCI_A_profile:
      as: 
      - 65000
      - 65178
      include_in_underlay_protocol: true
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
  - id: 1
    nodes: [BB1, A-LEAF7]
    interfaces: [Ethernet1, Ethernet7]
    profile: DCI_A_profile
    ip:
      - 172.16.1.0/31
      - 172.16.1.1/31
  - id: 2
    nodes: [BB2, A-LEAF7]
    interfaces: [Ethernet1, Ethernet8]
    profile: DCI_A_profile
    ip:
      - 172.16.1.4/31
      - 172.16.1.5/31
  - id: 3
    nodes: [BB1, A-LEAF8]
    interfaces: [Ethernet2, Ethernet7]
    profile: DCI_A_profile
    ip:
      - 172.16.1.2/31
      - 172.16.1.3/31
  - id: 4
    nodes: [BB2, A-LEAF8]
    interfaces: [Ethernet2, Ethernet8]
    profile: DCI_A_profile
    ip:
      - 172.16.1.6/31
      - 172.16.1.7/31
    
custom_templates:
  - vxlan-mcast-overlay.j2
