---

dc_name: backbone
pod_name: pod-bb

type: backbone

csc_prefix_lists:
  - name: PL-LOOPBACKS-EVPN-OVERLAY
    sequence_numbers:
      - sequence: 30
        action: 'permit 1.1.0.0/16 eq 32'

backbone:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 1.1.0.0/24
    bgp_as: 65000
    bgp_cluster_id: 1.1.0.0
    
  nodes: 
    - name: BB1
      id: 1 
      mgmt_ip: 192.168.0.9/24 
    - name: BB2
      id: 2
      mgmt_ip: 192.168.0.10/24
