---
servers:
  - name: HostA
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostA
          mode: active

  - name: HostB
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostB
          mode: active

  - name: HostC
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF3 ]
        vlans: 50
        mode: access
        spanning_tree_portfast: edge
        description: HostC

  - name: HostD
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF3, A-LEAF4 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostD
          mode: active
        
  - name: HostE
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF4 ]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        description: HostE

  - name: HostF
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF5, A-LEAF6 ]
        vlans: 70
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostF
          mode: active

  - name: HostG
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ B-LEAF1, B-LEAF2 ]
        vlans: 70
        mode: access
        spanning_tree_portfast: edge
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: HostG
          mode: active
          short_esi: 1111:2222:0007

  - name: HostH
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ B-LEAF1, B-LEAF2 ]
        vlans: 40
        mode: access
        spanning_tree_portfast: edge
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: HostH
          mode: active
          short_esi: 1111:2222:0008

  - name: HostI
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ B-LEAF3 ]
        vlans: 60
        mode: access
        spanning_tree_portfast: edge
        description: HostI
  
  - name: HostJ
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ B-LEAF3, B-LEAF4 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: HostJ
          mode: active
          short_esi: 3333:4444:0008

  - name: HostK
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ B-LEAF4 ]
        vlans: 70
        mode: access
        spanning_tree_portfast: edge
        description: HostK

  - name: HostL
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet3 ]
        switches: [ B-SW1 ]
        vlans: 40
        mode: access
        spanning_tree_portfast: edge
        description: HostL
    
  - name: HostM
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet4 ]
        switches: [ B-SW1 ]
        vlans: 80
        mode: access
        spanning_tree_portfast: edge
        description: HostM
        
  - name: HostN
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF1, C-LEAF2 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostN
          mode: active

  - name: HostO
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF3 ]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        description: HostO

  - name: HostP
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF3, C-LEAF4 ]
        vlans: 60
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostP
          mode: active

  - name: HostQ
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF4 ]
        vlans: 50
        mode: access
        spanning_tree_portfast: edge
        description: HostQ

  - name: HostR
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostR
          mode: active
  
  - name: HostS
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 60
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: HostS
          mode: active

network_ports:
  - switches:
      - B-LEAF5
      - B-LEAF6
    switch_ports:
      - Ethernet7
    enabled: true
    mode: trunk
    vlans: "40,80"
    spanning_tree_portfast: edge
    link_tracking:
      enabled: true
      name: CORE-LINKS
    ethernet_segment:
      short_esi: 7777:8888:0008
      redundancy: single-active
      designated_forwarder_algorithm: preference
      designated_forwarder_preferences: 
        - 2000
        - 1000
      dont_preempt: true
    description: AA_TO_B-SW1
