---

underlay_routing_protocol: isis
overlay_routing_protocol: ibgp

underlay_multicast: true
evpn_multicast: true

bgp_peer_groups:
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==
  evpn_overlay_core:
    password: 4b21pAdCvWeAqpcKDFMdWw==
    structured_config:
      local_as: 65500
      remove_private_as:
        replace_as: true
spine:
  defaults:
    platform: vEOS-lab 
    loopback_ipv4_pool: 10.0.0.64/24
    isis_system_id_prefix: '0000.0001'
    bgp_as: 65200
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes: 
    - name: B-SPINE1
      id: 1 
      mgmt_ip: 192.168.0.15/24 
    - name: B-SPINE2
      id: 2
      mgmt_ip: 192.168.0.16/24
    - name: B-SPINE3
      id: 3
      mgmt_ip: 192.168.0.17/24 
    - name: B-SPINE4
      id: 4
      mgmt_ip: 192.168.0.18/24

l3leaf:
  defaults:
    platform: vEOS-lab 
    loopback_ipv4_pool: 10.0.0.64/26
    loopback_ipv4_offset: 4
    vtep_loopback_ipv4_pool: 10.2.2.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4'] 
    uplink_switches: ['B-SPINE1', 'B-SPINE2', 'B-SPINE3', 'B-SPINE4']
    uplink_ipv4_pool: 192.168.1.0/24
    mlag_interfaces: ['Ethernet5', 'Ethernet6'] 
    mlag_peer_ipv4_pool: 10.0.0.0/31
    mlag_peer_l3_ipv4_pool: 192.0.0.0/31
    mlag_port_channel_id: 1000
    mlag_domain_id: "100"
    virtual_router_mac_address: 00:1c:73:00:00:01
    spanning_tree_root_super: true
    spanning_tree_mode: rapid-pvst
    bgp_as: 65200
    isis_system_id_prefix: '0000.0001'
    link_tracking:
      enabled: true
      groups:
        - name: CORE-LINKS
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes:
    - name: B-LEAF1
      id: 1
      mgmt_ip: 192.168.0.111/24
      uplink_switch_interfaces: 
        - Ethernet1
        - Ethernet1
        - Ethernet1
        - Ethernet1
    - name: B-LEAF2
      id: 2
      mgmt_ip: 192.168.0.112/24
      uplink_switch_interfaces:
        - Ethernet2
        - Ethernet2
        - Ethernet2
        - Ethernet2
    - name: B-LEAF3
      id: 3
      mgmt_ip: 192.168.0.113/24
      uplink_switch_interfaces: 
        - Ethernet3
        - Ethernet3
        - Ethernet3
        - Ethernet3
    - name: B-LEAF4
      id: 4
      mgmt_ip: 192.168.0.114/24
      uplink_switch_interfaces:
        - Ethernet4
        - Ethernet4
        - Ethernet4
        - Ethernet4
    - name: B-LEAF5
      id: 5
      mgmt_ip: 192.168.0.115/24
      uplink_switch_interfaces: 
        - Ethernet5
        - Ethernet5
        - Ethernet5
        - Ethernet5
    - name: B-LEAF6
      id: 6
      mgmt_ip: 192.168.0.116/24
      uplink_switch_interfaces:
        - Ethernet6
        - Ethernet6
        - Ethernet6
        - Ethernet6
  node_groups:       
    - group: DOMAIN_B_EVPNGW
      bgp_as: 65200
      evpn_gateway:
        # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
        remote_peers:
          - hostname: BB1
            bgp_as: 65500
            ip_address: 172.16.0.1
          - hostname: BB2
            bgp_as: 65500
            ip_address: 172.16.0.2
      raw_eos_cli: |
        dhcp relay
          mlag peer-link requests disabled
        agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
      nodes:
        - name: B-LEAF7
          id: 7
          mgmt_ip: 192.168.0.117/24
          uplink_switch_interfaces: 
            - Ethernet7
            - Ethernet7
            - Ethernet7
            - Ethernet7
        - name: B-LEAF8
          id: 8
          mgmt_ip: 192.168.0.118/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
            - Ethernet8
            - Ethernet8

l2leaf:
  defaults:
    platform: vEOS-lab
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['B-LEAF5','B-LEAF6']
    spanning_tree_mode: rapid-pvst
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes:
    - name: B-SW1
      id: 1
      mgmt_ip: 192.168.0.119/24
      uplink_switch_interfaces:
        - Ethernet7
        - Ethernet7
      
