---

- name: Configuration deployment
  hosts: FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.deploy_to_cv
      vars:
        deploy_to_cv_accept_preview: true
        cv_server: 10.255.53.196
        cv_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjczMzgwOTk4OTYwNzY5OTI3MTYsImRzbiI6ImNpLXJ1bm5lciIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3Mzg0MjA2MzAsImlhdCI6MTcwODYxMjYzNCwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiNWM1ODZjOGQyMjdlM2EwYTM1YzE2ZTE1ZWViZDU3Y2VkZWI3N2E3NDY5NzU5OTRiMjVhMmE2OTRiN2Q2OGNjMi1UcmJ3NERERTloNjFNcXZIbHF0SkZFbEdIU2ZwR2VCM044ZkRKWHc4In0.Ubl9k6eaYw8O0-_FMIJ3HkzZsN4H5DEkNc2xqngJ7q69zD_Wvvh8lIExcQ6moXsZMnftkK2mfk1-5XSm53o0xWpL-w38v3q4DAbrvyKyKi8kdvPZwmfZrkHG-Ex9pF8eISYowndgWZYpHzS9i5Lqsuz2wCeKL4pp6TCEUf9GHmEEsv6LDaqrHjofoM_raxgFg4irEngNZpDQoy8WTPijpgJ6NXA_Y_lujzICK9nCWCUT3j55Co72W8DPDLoeWp6mzEeLPND8w57z_GvLo1OhSZ4E3T4OHkHvfzedToyfCfauS2ZHUOwDnJVDRjGy-qx0hTCi9C4YlkIvnKVeOeObwjLNZrcZ5xtzu-A20ijdz4W47N62ibGOzFd8nezV9v8Onh29STjBxIeMJJlovRhq8Hx4cmLFUzZJt18hveflvxEwJoKKVaokYNOY-z3ZIWav-FHTynpA-cspjTUkUXy9pvIV7LZ5tdLlBaVeJ8_Ey63VbbM-RWb52Wq5Zohg7mM3HB-XZyWdIrFg4wUewqyXYaykUndqe4bjKjURRWr144wm4PNHIA-tN4GmHkEbYOc0sgsYh6kMIYn7cZ434AF32iCCI2EQYx3mgKP4EXcTBz5VxE11O5yRpvIxsdhd-KQD9irfBaq8Ihm_aLu9q2Z_QNZ-su9vsjqSyzlbiCCysSA"
        cv_verify_certs: false
