---

- name: Configuration deployment
  hosts: FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.deploy_to_cv
      vars:
        deploy_to_cv_accept_preview: true
        cv_server: 10.255.53.196
        cv_token: "{{ lookup('env', 'CV_DEPLOY_TOKEN')}}"
        cv_verify_certs: false
