- name: Configuration deployment
  hosts: FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.deploy_to_cv
      vars:
        cv_server: 10-255-110-207.act.arista.com
        cv_token: "{{ lookup('env', 'cv_svc_token') }}"
        deploy_to_cv_accept_preview: true
        cv_inventory_hostname: act_cv
        cv_verify_certs: false
        cv_workspace_name: ns
