---

- name: Push switch configs
  hosts: all
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    config_dir: "{{ playbook_dir }}/../configs/"
  vars_files:
    - "./host_networking.yml"
  tasks:

    - name: "Configure et1 ip address"
      ansible.builtin.shell: |
        ip addr add {{ hostnets[inventory_hostname].ip }} dev {{ hostnets[inventory_hostname].int }}
        ip route add 10.40.40.0/24 via {{ hostnets[inventory_hostname].gw }}
      register: test
      become: yes
      when: "{{ 'HOST' in inventory_hostname }}"