---

port_profiles:
  - profile: DEFAULT
    spanning_tree_portfast: edge
    mode: access

servers:
  - name: C1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF1, C-LEAF2 ]
        vlans: 10
        profile: DEFAULT
        port_channel:
          description: C1
          mode: active

  - name: C2
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF3 ]
        vlans: 20
        profile: DEFAULT
        description: C2

  - name: C3
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF3, C-LEAF4 ]
        vlans: 60
        profile: DEFAULT
        port_channel:
          description: C3
          mode: active

  - name: C4
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF4 ]
        vlans: 50
        profile: DEFAULT
        description: C4

  - name: C5
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 20
        profile: DEFAULT
        port_channel:
          description: C5
          mode: active
  
  - name: C6
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 60
        profile: DEFAULT
        port_channel:
          description: C6
          mode: active
