---

type: l3leaf
cv_tags_topology_type: leaf

evpn_multicast: false
underlay_multicast: false

router_general:
  control_functions:
    code_units:
      - name: evpngw-rcf
        content: |-
          function PREFIX_ROUTE() {
            return evpn.route_type is EVPN_IP_PREFIX;
          }
          function IMET_ROUTE() {
            return evpn.route_type is EVPN_IMET;
          }
          function FROM_GW_PEER() {
            return community has_any {2:2};
          }
          function GW_LOOPBACK() {
            return prefix match prefix_list_v4 PL-GATEWAY-LOOP;
          }
          function AS65000_OUT_IPV4() {
            if GW_LOOPBACK(){
              return true;
            }
            return false;
          }
          function AS65000_OUT_EVPN() {
            if IMET_ROUTE() or PREFIX_ROUTE(){
              community add {2:2};
            }
            return true;
          }
          function AS65000_IN_EVPN() {
            if (IMET_ROUTE() or PREFIX_ROUTE()) and FROM_GW_PEER() {
              return false;
            }
            return true;
          }
          function AS65200_OUT_EVPN() { 
            if PREFIX_ROUTE(){
              community add {2:2};
            }
            return true;
          }
          function AS65200_IN_EVPN() { 
            if PREFIX_ROUTE() and FROM_GW_PEER() {
              return false;
              }
            return true;
          }
          EOF

custom_templates:
  - evpngw-af-evpn.j2
