---
fabric_name: FABRIC 

underlay_routing_protocol: isis
overlay_routing_protocol: ibgp

isis_area_id: 49.1111
evpn_short_esi_prefix: '0000:000b:'

underlay_multicast: true

p2p_uplinks_mtu: 1500

l3_edge:
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    DCI_B_profile:
      include_in_underlay_protocol: false
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
  - id: 1
    nodes: [BB1, B-LEAF7]
    interfaces: [Ethernet3, Ethernet7]
    profile: DCI_B_profile
    ip:
      - 172.16.2.0/31
      - 172.16.2.1/31
  - id: 2
    nodes: [BB2, B-LEAF7]
    interfaces: [Ethernet3, Ethernet8]
    profile: DCI_B_profile
    ip:
      - 172.16.2.4/31
      - 172.16.2.5/31
  - id: 3
    nodes: [BB1, B-LEAF8]
    interfaces: [Ethernet4, Ethernet7]
    profile: DCI_B_profile
    ip:
      - 172.16.2.2/31
      - 172.16.2.3/31
  - id: 4
    nodes: [BB2, B-LEAF8]
    interfaces: [Ethernet4, Ethernet8]
    profile: DCI_B_profile
    ip:
      - 172.16.2.6/31
      - 172.16.2.7/31

custom_templates:
  - vxlan-mcast-overlay.j2
  - dom-b-template.j2
