---
type: l3leaf

dhcp_relay:
  tunnel_requests_disabled: true
  mlag_peerlink_requests_disabled: true

ip_extcommunity_lists_regexp:
  - name: 'evpn-imported'
    entries:
      - type: 'permit'
        regexp: 'RT.*'
