---
fabric_name: FABRIC 

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

underlay_multicast: false
evpn_multicast: false

underlay_ipv6: true
underlay_rfc5549: true
overlay_mlag_rfc5549: true
overlay_routing_protocol_address_family: ipv6

fabric_ip_addressing:
  mlag:
    algorithm: same_subnet

bgp_peer_groups:
  evpn_overlay_core:
    structured_config:
      local_as: 65000
      remove_private_as:
        replace_as: true
      bfd: false
  ipv4_underlay_peers:
    name: LOCAL-UNDERLAY-PEERS

l3_edge:
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    DCI_D_profile:
      as: 
      - 65000
      - 65478
      include_in_underlay_protocol: true
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
  - id: 1
    nodes: [BB1, D-LEAF7]
    interfaces: [Ethernet7, Ethernet7]
    profile: DCI_D_profile
    ip:
      - 172.16.4.0/31
      - 172.16.4.1/31
  - id: 2
    nodes: [BB2, D-LEAF7]
    interfaces: [Ethernet7, Ethernet8]
    profile: DCI_D_profile
    ip:
      - 172.16.4.4/31
      - 172.16.4.5/31
  - id: 3
    nodes: [BB1, D-LEAF8]
    interfaces: [Ethernet8, Ethernet7]
    profile: DCI_D_profile
    ip:
      - 172.16.4.2/31
      - 172.16.4.3/31
  - id: 4
    nodes: [BB2, D-LEAF8]
    interfaces: [Ethernet8, Ethernet8]
    profile: DCI_D_profile
    ip:
      - 172.16.4.6/31
      - 172.16.4.7/31
