---

- name: Push switch configs
  connection: httpapi
  hosts: all
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    config_dir: "{{ playbook_dir }}/../configs/"

  tasks:

    - name: "Push configs to EOS nodes from {{ config_dir }}"
      eos_config:
        src: "{{ config_dir }}{{ inventory_hostname }}.cfg"
        replace: config
        save_when: changed
      when: 'HOST' not in {{ inventory_hostname }}

    - name: "Configure end hosts"
      eos_config:
        src: "{{ config_dir }}{{ inventory_hostname }}.cfg"
        replace: config
        save_when: changed
      when: 'HOST' in {{ inventory_hostname }}