---

csc_router_bgp:
  address_family_ipv4:
    networks:
      - prefix: 1.1.0.1/32
  listen_ranges:
    - prefix: 1.1.0.0/16
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65000

csc_ethernet_interfaces:
  - name: Ethernet9
    shutdown: false
    ip_address: 172.16.255.0/31
    type: routed
