---
name: build techlib-labs containers

on:
  push:
    branches: ['**']  # branches will be filtered in the jobs
    paths:
      - .github/workflows/container_build_child.yml
      - .github/workflows/container_build_parent_matrix.yml
      - containers/techlib-labs/**
  workflow_dispatch:
    branches: ['**']  # branches will be filtered in the jobs

permissions:
  packages: write

jobs:
  build-lab-containers:
    # fork - build container from any branch for testing
    # parent repo - build on main branch only
    if: github.repository != 'aristanetworks/acLabs' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/container_build_child.yml
    strategy:
      matrix:
        from_image: ["ghcr.io/aristanetworks/avd/universal"]
        from_variant: ["python3.11-avd-v4.9.0", "python3.11-avd-v4.10.0"]
        clab_version: ["0.54.2", "0.56.0"]
        ceos_lab_version: ["4.32.1F", "4.32.2F"]
    with:
      from_image: ${{ matrix.from_image }}
      from_variant: ${{ matrix.from_variant }}
      clab_version: ${{ matrix.clab_version }}
      ceos_lab_version: ${{ matrix.ceos_lab_version }}
