---

port_profiles:
  - profile: DEFAULT
    spanning_tree_portfast: edge
    mode: access

servers:
  - name: B1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ B-LEAF1, B-LEAF2 ]
        profile: DEFAULT
        vlans: 20
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: B1
          mode: active
        ethernet_segment:
          short_esi: 0001:0002:0007

  - name: B2
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ B-LEAF1, B-LEAF2 ]
        profile: DEFAULT
        vlans: 40
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: B2
          mode: active
        ethernet_segment:
          short_esi: 0001:0002:0008

  - name: B3
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ B-LEAF3 ]
        profile: DEFAULT
        vlans: 60
        description: B3
  
  - name: B4
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ B-LEAF3, B-LEAF4 ]
        profile: DEFAULT
        vlans: 10
        link_tracking:
          enabled: true
          name: CORE-LINKS
        ethernet_segment:
          short_esi: 0003:0004:0008
        port_channel:
          description: B4
          mode: active

  - name: B5
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ B-LEAF4 ]
        profile: DEFAULT
        vlans: 70
        description: B5

  - name: B6
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet3 ]
        switches: [ B-SW1 ]
        profile: DEFAULT
        vlans: 40
        description: B6
    
  - name: B7
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet4 ]
        switches: [ B-SW1 ]
        profile: DEFAULT
        vlans: 80
        description: B7
  
  # - name: B-SW1-1
  #   adapters:
  #     - switch_ports:
  #         - Ethernet7
  #       switches:
  #         - B-LEAF5
  #       endpoint_ports:
  #         - Ethernet1
  #       mode: trunk
  #       vlans: "40,80"
  #       spanning_tree_bpduguard: false
  #       link_tracking:
  #         enabled: True
  #         name: CORE-LINKS
  #       ethernet_segment:
  #         short_esi: 0005:0006:0007
  #         redundancy: single-active
  #         designated_forwarder_algorithm: preference
  #         designated_forwarder_preferences: 
  #           - 2000
  #         dont_preempt: true 
  #       description: B-SW1
network_ports:
  - switches:
      - B-LEAF5
      - B-LEAF6
    switch_ports:
      - Ethernet7
    enabled: true
    mode: trunk
    vlans: "40,80"
    spanning_tree_portfast: edge
    link_tracking:
      enabled: true
      name: CORE-LINKS
    description: B-SW1
  - switches:
      - B-SW1
    switch_ports:
      - Ethernet1-2
    enabled: true
    mode: trunk
