# # L3 Edge port definitions. This can be any port in the entire Fabric, where IP interfaces are defined.
l3_edge:
  # Define a new IP pool that will be used to asign IP addreses to L3 Edge interfaces.
  p2p_links_ip_pools:
    B_IP_pool: 172.16.2.0/24
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    DCI_B_profile:
      ip_pool: B_IP_pool
      as:
      - 65200
      - 65500
      include_in_underlay_protocol: false
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
  - id: 1
    nodes: [B-LEAF7, BB1]
    interfaces: [Ethernet7, Ethernet3]
    profile: DCI_B_profile
  - id: 2
    nodes: [B-LEAF7, BB2]
    interfaces: [Ethernet8, Ethernet3]
    profile: DCI_B_profile
  - id: 3
    nodes: [B-LEAF8, BB1]
    interfaces: [Ethernet7, Ethernet4]
    profile: DCI_B_profile
  - id: 4
    nodes: [B-LEAF8, BB2]
    interfaces: [Ethernet8, Ethernet4]
    profile: DCI_B_profile
