---
type: l3leaf
evpn_multicast: false
underlay_multicast: false
  
custom_structured_configuration_router_bgp:
  address_family_ipv4:
    peer_groups:
      - name: IPv4-REMOTE-UNDERLAY-PEERS
        activate: true
